### ISSUE TITLE
Tools crash

### ISSUE THREAD

**Issue by FlaviuNistor** [timoothee/CAN-Tester#34]
When pressing the UP button to set up the CAN interfaces, the GUI crashes with the next error:

![image](https://user-images.githubusercontent.com/33119909/227891227-d5d84760-2b28-45f6-97e8-fbdd868ee7cc.png)

**Comment by timoothee** [comment]
Found it, working on it

**Comment by FlaviuNistor** [comment]
I will wait for the fix and try again tomorrow (after a git pull, main branch)
