### ISSUE TITLE
Import que from file

### ISSUE THREAD

**Issue by FlaviuNistor** [timoothee/CAN-Tester#44]
When importing que from file, the "new line" \n character is also displayed in the que list of the tool (see the squar at the end of the lines).
This is not a big issue and is not critical since the tool will still work, but could have in mind to solve it.

![image](https://user-images.githubusercontent.com/33119909/228521776-29588a06-eec0-4982-a822-320d17378072.png)

**Comment by timoothee** [comment]
Done.
Correction that will be added in the next release. (1.8.1)
