### ISSUE TITLE
Extended ID

### ISSUE THREAD

**Issue by FlaviuNistor** [timoothee/CAN-Tester#45]
When selecting EXT ID a wrong number of digits is allowed. In the picture you can see that ID 112345678 is accepted, but this is to big. See on the left side there is an error given by cansend. The intended ID was 12345678.

If I edit the message and remove the first digit ('1'), all works again.

![image](https://user-images.githubusercontent.com/33119909/228522469-6211212f-bee0-4e8a-bf73-89d16a5de0a1.png)

**Comment by timoothee** [comment]
Done. 
Correction that will be added in the next release. (1.8.1)
